plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - type: major
          release: major
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: build
          release: patch
        - type: chore
          release: patch
        - type: ci
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: revert
          release: patch
        - type: test
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: major
            section: ":rotating_light: Breaking Changes"
            hidden: false
          - type: feat
            section: ":bulb: Features"
            hidden: false
          - type: fix
            section: ":beetle: Bug Fixes"
            hidden: false
          - type: build
            section: ":package: Build Adjustments"
            hidden: false
          - type: chore
            section: ":hammer: Dependency Updates"
            hidden: false
          - type: perf
            section: ":rocket: Performance Improvements"
            hidden: false
          - type: refactor
            section: ":gear: Refactoring"
            hidden: false
          - type: revert
            section: ":leftwards_arrow_with_hook: Revert"
            hidden: false
          - type: test
            section: ":unicorn: Quality Assurance"
            hidden: false
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/gitlab"
branches:
  - "main"
