name: build
run-name: "verifying integrity"

on:
  push:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./gradlew compileKotlin compileTestKotlin compileJava compileTestJava

  owasp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./gradlew dependencyCheckAnalyze
      - uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: build/reports/dependency-check-report.html

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./gradlew ktlintCheck
      - uses: actions/upload-artifact@v3
        with:
          name: ktlint-reports
          path: build/reports/ktlint/*

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./gradlew unitTests
      - uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: build/reports/tests/unitTests/*

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./gradlew integrationTests
      - uses: actions/upload-artifact@v3
        with:
          name: integration-test-report
          path: build/reports/tests/integrationTests/*

  architecture-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./gradlew architectureTests
      - uses: actions/upload-artifact@v3
        with:
          name: architecture-test-report
          path: build/reports/tests/architectureTests/*

  test-coverage-verification:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-tests
      - architecture-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/download-artifact@v3
        with:
          name: unit-test-report
          path: build/reports/tests/unitTests/*
      - uses: actions/download-artifact@v3
        with:
          name: integration-test-report
          path: build/reports/tests/integrationTests/*
      - uses: actions/download-artifact@v3
        with:
          name: architecture-test-report
          path: build/reports/tests/architectureTests/*
      - run: ./gradlew jacocoTestCoverageVerification

  test-coverage-report:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-tests
      - architecture-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/download-artifact@v3
        with:
          name: unit-test-report
          path: build/reports/tests/unitTests/*
      - uses: actions/download-artifact@v3
        with:
          name: integration-test-report
          path: build/reports/tests/integrationTests/*
      - uses: actions/download-artifact@v3
        with:
          name: architecture-test-report
          path: build/reports/tests/architectureTests/*
      - run: ./gradlew jacocoTestReport
      - uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: build/reports/jacoco/test/html/*
