name: build
run-name: "${{ github.ref_name }}: verifying \"${{ github.event.head_commit.message }}\""

on:
    push:
    workflow_dispatch:

jobs:

  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
      - name: compile code
        run: ./gradlew compileKotlin compileTestKotlin compileJava compileTestJava
      - uses: actions/upload-artifact@v3
        with:
          name: compile
          path: build

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: lint code
        run: ./gradlew ktlintCheck
      - uses: actions/upload-artifact@v3
        with:
          name: ktlint-reports
          path: build/reports/ktlint/*

  unit-tests:
    runs-on: ubuntu-latest
    needs: [ compile ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
      - uses: actions/download-artifact@v3
        with:
          name: compile
          path: build
      - name: run unit tests
        run: ./gradlew unitTests
      - uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: build/reports/tests/unitTests/*
      - uses: actions/upload-artifact@v3
        with:
          name: unit-test-execution-data
          path: build/jacoco/unitTests.exec

  integration-tests:
    runs-on: ubuntu-latest
    needs: [ compile ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
      - uses: actions/download-artifact@v3
        with:
          name: compile
          path: build
      - name: run integration tests
        run: ./gradlew integrationTests
      - uses: actions/upload-artifact@v3
        with:
          name: integration-test-report
          path: build/reports/tests/integrationTests/*
      - uses: actions/upload-artifact@v3
        with:
          name: integration-test-execution-data
          path: build/jacoco/integrationTests.exec

  architecture-tests:
    runs-on: ubuntu-latest
    needs: [ compile ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
      - uses: actions/download-artifact@v3
        with:
          name: compile
          path: build
      - name: run architecture tests
        run: ./gradlew architectureTests
      - uses: actions/upload-artifact@v3
        with:
          name: architecture-test-report
          path: build/reports/tests/architectureTests/*
      - uses: actions/upload-artifact@v3
        with:
          name: architecture-test-execution-data
          path: build/jacoco/architectureTests.exec

  test-coverage-verification:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-tests
      - architecture-tests
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
      - uses: actions/download-artifact@v3
        with:
          name: compile
          path: build
      - uses: actions/download-artifact@v3
        with:
          name: unit-test-execution-data
          path: build/jacoco/unitTests.exec
      - uses: actions/download-artifact@v3
        with:
          name: integration-test-execution-data
          path: build/jacoco/integrationTests.exec
      - uses: actions/download-artifact@v3
        with:
          name: architecture-test-execution-data
          path: build/jacoco/architectureTests.exec
      - name: verify code coverage
        # for some reason downloaded test execution data is not used, so we'll run all tests again for jacoco to work
        run: ./gradlew test jacocoTestCoverageVerification

  test-coverage-report:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-tests
      - architecture-tests
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
      - uses: actions/download-artifact@v3
        with:
          name: compile
          path: build
      - uses: actions/download-artifact@v3
        with:
          name: unit-test-execution-data
          path: build/jacoco/unitTests.exec
      - uses: actions/download-artifact@v3
        with:
          name: integration-test-execution-data
          path: build/jacoco/integrationTests.exec
      - uses: actions/download-artifact@v3
        with:
          name: architecture-test-execution-data
          path: build/jacoco/architectureTests.exec
      - name: create code coverage report
        # for some reason downloaded test execution data is not used, so we'll run all tests again for jacoco to work
        run: ./gradlew test jacocoTestReport
      - uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: build/reports/jacoco/test/html/*
