name: owasp
run-name: "checking for known vulnerabilities"

on:
    schedule: [ cron: "0 0 * * *" ]
    workflow_dispatch:

jobs:

  owasp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: check dependencies for vulnerabilities
        env:
            NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: ./gradlew dependencyCheckAnalyze
      - uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: build/reports/dependency-check-report.html
